OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    # Specs:
    #   - Hostname: orderer
    Template: 
      Count: 3

PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1: Utility Company
  # ---------------------------------------------------------------------------
  - Name: Buyer
    Domain: buyer.example.com
  # ---------------------------------------------------------------------------
  #No. of peers defined for utility:
  # ---------------------------------------------------------------------------
    Template:
      Count: 2
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 3

#==================================================================================
  # ---------------------------------------------------------------------------
  # Org2: Solar Installations
  # ---------------------------------------------------------------------------
  - Name: Seller
    Domain: seller.example.com
  # ---------------------------------------------------------------------------
  #No. of peers defined for utility:
  # ---------------------------------------------------------------------------
    Template:
      Count: 2
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 3